[package]
name = "fast-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
blake3 = "1.8.2"
bytes = "1.10.1"
inotify = "0.11.0"
memmap2 = "0.9.9"
tokio = { version = "1.48.0", features = ["full"] }
